Removing duplication from TH output
yesodweb/persistent pull request #1202
Opened 2021-03-14 23:19 UTC by danbroooks

Before submitting your PR, check that you've:

- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

-----

I'm submitting this draft PR for some initial feedback, as I think I have found a potential optimisation which drops some duplication from the resulting output. The `FieldDef`s are accessible already via `persistFieldDef` so I thought it might bring down the total code output by making that call to get at the field defs when building up the `EntityDef`, rather than inlining the definitions. I'm not sure if there are implications to this so would appreciate some feedback if this is going to have negative effects, but AFAICT this is a reasonable change to make, though there may be some reason why this isn't done like this currently. I'm not sure on how much of a difference this will make to improved compile times but every little helps I suppose, and I think this will have an impact on a real world project where the are a large total number of fields.

```diff
diff --git a/persistent-template/OverloadedLabelTest.dump-splices b/persistent-template/OverloadedLabelTest.dump-splices
index e157c29b..026b74a5 100644
--- a/persistent-template/OverloadedLabelTest.dump-splices
+++ b/persistent-template/OverloadedLabelTest.dump-splices
@@ -534,55 +534,36 @@ test/OverloadedLabelTest.hs:(20,1)-(34,2): Splicing declarations
                         Nothing)
                        Nothing))
                    [])
-                  [(((((((((FieldDef (FieldNameHS (Data.Text.pack "name")))
-                             (FieldNameDB (Data.Text.pack "name")))
-                            ((FTTypeCon Nothing) (Data.Text.pack "String")))
-                           SqlString)
-                          [])
-                         True)
-                        NoReference)
-                       ((FieldCascade Nothing) Nothing))
-                      Nothing)
-                     Nothing,
-                   (((((((((FieldDef (FieldNameHS (Data.Text.pack "age")))
-                             (FieldNameDB (Data.Text.pack "age")))
-                            ((FTTypeCon Nothing) (Data.Text.pack "Int")))
-                           SqlInt64)
-                          [])
-                         True)
-                        NoReference)
-                       ((FieldCascade Nothing) Nothing))
-                      Nothing)
-                     Nothing])
+                  [persistFieldDef UserName, persistFieldDef UserAge])
                  [])
                 [])
                [])
               (containers-0.6.0.1:Data.Map.Internal.fromList []))
              False)
             Nothing
-      toPersistFields (User x_aKxA x_aKxB)
-        = [SomePersistField x_aKxA, SomePersistField x_aKxB]
-      fromPersistValues [x1_aKxD, x2_aKxE]
+      toPersistFields (User x_aKro x_aKrp)
+        = [SomePersistField x_aKro, SomePersistField x_aKrp]
+      fromPersistValues [x1_aKrr, x2_aKrs]
         = User
             <$>
               (Database.Persist.TH.mapLeft
                  ((fieldError (Data.Text.pack "User")) (Data.Text.pack "name"))
                  . fromPersistValue)
-                x1_aKxD
+                x1_aKrr
             <*>
               (Database.Persist.TH.mapLeft
                  ((fieldError (Data.Text.pack "User")) (Data.Text.pack "age"))
                  . fromPersistValue)
-                x2_aKxE
-      fromPersistValues x_aKxC
+                x2_aKrs
+      fromPersistValues x_aKrq
         = (Left
              $ (mappend (Data.Text.pack "User: fromPersistValues failed on: "))
-                 (Data.Text.pack $ show x_aKxC))
+                 (Data.Text.pack $ show x_aKrq))
       persistUniqueToFieldNames _
         = error "Degenerate case, should never happen"
       persistUniqueToValues _
         = error "Degenerate case, should never happen"
-      persistUniqueKeys (User _name_aKxF _age_aKxG) = []
+      persistUniqueKeys (User _name_aKrt _age_aKru) = []
       persistFieldDef UserId
         = (((((((((FieldDef (FieldNameHS (Data.Text.pack "Id")))
                     (FieldNameDB (Data.Text.pack "id")))
@@ -621,15 +602,15 @@ test/OverloadedLabelTest.hs:(20,1)-(34,2): Splicing declarations
       persistIdField = UserId
       fieldLens UserId
         = (lensPTH entityKey)
-            (\ (Entity _ value_aKxH) key_aKxI -> (Entity key_aKxI) value_aKxH)
+            (\ (Entity _ value_aKrv) key_aKrw -> (Entity key_aKrw) value_aKrv)
       fieldLens UserName
         = (lensPTH (userName . entityVal))
-            (\ (Entity key_aKxJ value_aKxK) x_aKxL
-               -> (Entity key_aKxJ) value_aKxK {userName = x_aKxL})
+            (\ (Entity key_aKrx value_aKry) x_aKrz
+               -> (Entity key_aKrx) value_aKry {userName = x_aKrz})
       fieldLens UserAge
         = (lensPTH (userAge . entityVal))
-            (\ (Entity key_aKxJ value_aKxK) x_aKxL
-               -> (Entity key_aKxJ) value_aKxK {userAge = x_aKxL})
+            (\ (Entity key_aKrx value_aKry) x_aKrz
+               -> (Entity key_aKrx) value_aKry {userAge = x_aKrz})
     instance ToBackendKey SqlBackend User where
       toBackendKey = unUserKey
       fromBackendKey = UserKey
@@ -679,73 +660,43 @@ test/OverloadedLabelTest.hs:(20,1)-(34,2): Splicing declarations
                         Nothing)
                        Nothing))
                    [])
-                  [(((((((((FieldDef (FieldNameHS (Data.Text.pack "userId")))
-                             (FieldNameDB (Data.Text.pack "userId")))
-                            ((FTTypeCon Nothing) (Data.Text.pack "UserId")))
-                           (sqlType (Data.Proxy.Proxy :: Data.Proxy.Proxy GHC.Int.Int64)))
-                          [])
-                         True)
-                        ((ForeignRef (EntityNameHS (Data.Text.pack "User")))
-                           ((FTTypeCon (Just (Data.Text.pack "Data.Int")))
-                              (Data.Text.pack "Int64"))))
-                       ((FieldCascade Nothing) Nothing))
-                      Nothing)
-                     Nothing,
-                   (((((((((FieldDef (FieldNameHS (Data.Text.pack "name")))
-                             (FieldNameDB (Data.Text.pack "name")))
-                            ((FTTypeCon Nothing) (Data.Text.pack "String")))
-                           SqlString)
-                          [])
-                         True)
-                        NoReference)
-                       ((FieldCascade Nothing) Nothing))
-                      Nothing)
-                     Nothing,
-                   (((((((((FieldDef (FieldNameHS (Data.Text.pack "age")))
-                             (FieldNameDB (Data.Text.pack "age")))
-                            ((FTTypeCon Nothing) (Data.Text.pack "Int")))
-                           SqlInt64)
-                          [])
-                         True)
-                        NoReference)
-                       ((FieldCascade Nothing) Nothing))
-                      Nothing)
-                     Nothing])
+                  [persistFieldDef DogUserId, persistFieldDef DogName,
+                   persistFieldDef DogAge])
                  [])
                 [])
                [])
               (containers-0.6.0.1:Data.Map.Internal.fromList []))
              False)
             Nothing
-      toPersistFields (Dog x_aKxM x_aKxN x_aKxO)
-        = [SomePersistField x_aKxM, SomePersistField x_aKxN,
-           SomePersistField x_aKxO]
-      fromPersistValues [x1_aKxQ, x2_aKxR, x3_aKxS]
+      toPersistFields (D [...]

2021-03-14 23:44 UTC, danbroooks commented
I guess CI has answered some of my questions, back to the drawing board I guess :)

2021-03-15 16:24 UTC, parsonsmatt commented
I wish we could collect metrics on when features were being used. The `*Generic` machinery is complicated and I'm not sure that it's actually useful at all.

I suppose we could deprecate it and see if anyone complained 🤔 

This feels like it should be fixable with a type annotation. All we want to do is use `persistFieldDef` at a specific backend type. That function is a class method with the type `persistFieldDef :: PersistEntity record => EntityField record typ -> FieldDef`. So we would want to annotate it with, like, `persistFieldDef (HtmlTableHtml :: EntityField (HtmlTableGeneric backend) ???)`. Then hopefully `backend` fixes to the right type variable and we don't need to fool around with `ScopedTypeVariables` or similar.

2021-03-22 23:08 UTC, parsonsmatt commented
@danbroooks I'm planning on releasing `persistent-2.12` this week. Would you like to attempt the fix I mentioned? I think it's good enough as-is - we can merge now and then put a note in to fix this more at some other time.

2021-03-22 23:34 UTC, danbroooks commented
Yeah, I've not had chance to take another look at this yet, my TH skills are not amazing either so you may need to bare with me on adding the type hints like you suggested (I have a feeling there will be an ambiguity issue still here, though happy to be wrong!).

As far as merging it in as it is currently, I would say maybe not, but that is up to you.

2021-03-24 14:26 UTC, danbroooks commented
@parsonsmatt you may want to take a look at this, this latest iteration (5108cec) is maybe a good compromise between a quick fix to get TH improvements into persistent but that is relatively clean (though leaving _some_ code duplication in place), further work could be done after this to clean things up, and I think deprecating `mpsGeneric` would help in this regard if nothing comes from your issue.

I'm sorry but I was unable to get your typehint suggestion to work, it also adds in some more complication with regards to what the `???` is in `EntityField (HtmlTableGeneric backend) ???`, as I think it needs to cover each of these references:

https://hackage.haskell.org/package/persistent-2.11.0.4/docs/Database-Persist-Types.html#t:ReferenceDef

So I ended up struggling with it a bit, unfortunately! I think this might be viable still (and there is some existing functionality to do this currently in the `TH` module I think, but it's not geared up for re-use as it stands currently). I'm willing to keep at it though, but if you like what is in this draft PR as it stands now, I am happy to convert it to a PR for review/merge :+1:

2021-03-26 19:45 UTC, parsonsmatt requested changes
One final change - then I think we can merge this one in :)

2021-03-26 19:45 UTC, parsonsmatt commented on persistent/Database/Persist/TH.hs
> +    lookupValueName "persistFieldDef" >>= \case
This feels a bit dicey. Why not use the name facility lie `'persistFieldDef` ? That gives you a qualified name that should work fine in the context without requiring it to be imported.

eg:

```haskell
fmap ListE $ forM fieldDefs $ \fieldDef -> do
  ...
    pure $ VarE 'persistFieldDef `AppE` fieldDefConE
```

2021-03-29 03:22 UTC, parsonsmatt approved these changes

2021-03-29 03:22 UTC, parsonsmatt commented
Looks fantastic thanks! Ready to merge?

2021-03-29 08:56 UTC, danbroooks commented
Sure! :tada:

2021-03-29 13:10 UTC, merged