Add insertUnique_ to PersistUniqueWrite
yesodweb/persistent pull request #1469
Opened 2023-01-27 01:34 UTC by lbseale

Before submitting your PR, check that you've:

- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock
- [x] Ran `stylish-haskell` on any changed files.
- [x] Adhered to the code style (see the `.editorconfig` file for details)

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

2023-01-27 01:34 UTC, lbseale commented
Fixes issue #1457

2023-03-02 18:36 UTC, parsonsmatt requested changes
This is great, thank you! Please make a Changelog entry. I'll relesae this with 2.14.5.0

2023-03-02 18:36 UTC, parsonsmatt commented on persistent/Database/Persist/Class/PersistUnique.hs
> +    -- @since 2.14.4.4
As an addition to a class with a default method, this is a minor version bump - let's bundle this with 2.15.0.

2023-03-03 16:31 UTC, parsonsmatt approved these changes
Thanks!

2023-03-03 16:59 UTC, merged

2023-03-03 17:06 UTC, lbseale commented
Thank you! Proud to have my contribution included